### PR TITLE
Remove redundant dependency on .NET Standard 2.0

### PR DESCRIPTION
**Pull request by bdovaz**

### CODE REVIEW

**Comment by bdovaz** [comment]
Your [PR](https://github.com/xoofx/UnityNuGet/pull/134) caused UnityNuGet registry to fail.

**Comment by tonygiang** [comment]
Would it work if I remove the dependency on `System.ValueTuple` only for the .netstandard2.0 assembly?

**Comment by bdovaz** [comment]
Of course, you can check it yourself.

**Comment by tonygiang** [comment]
Appreciated the PR. I have other changes I wanted to make for this package and made my own commit. Version 1.2.0 of this package is now live on NuGet. You can close this PR yourself if you find no further issue.

**Pull request closed without merging**
